# GNU Make project makefile autogenerated by Premake

ifndef config
  config=releasewithsymbols_x86
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),releasewithsymbols_x86_64)
  RESCOMP = windres
  TARGETDIR = x86_64/ReleaseWithSymbols
  TARGET = $(TARGETDIR)/gmsv_luapack_internal_linux64.dll
  OBJDIR = x86_64/ReleaseWithSymbols/intermediate/gmsv_luapack_internal
  DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DLUAPACK_INTERNAL_SERVER -DIS_SERVERSIDE=true -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"luapack_internal\" -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
  INCLUDES += -I../../../source -isystem ../../../garrysmod_common/include -isystem ../../../garrysmod_common/helpers/include -isystem ../../../garrysmod_common/helpers_extended/include -isystem ../../../garrysmod_common/sourcesdk-minimal/common -isystem ../../../garrysmod_common/sourcesdk-minimal/game/shared -isystem ../../../garrysmod_common/sourcesdk-minimal/public -isystem ../../../garrysmod_common/sourcesdk-minimal/game/server -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier0 -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier1 -isystem ../../../garrysmod_common/scanning/include -isystem ../../../garrysmod_common/detouring/include -isystem ../../../garrysmod_common/detouring/hde/include -isystem ../../../garrysmod_common/detouring/minhook/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/ReleaseWithSymbols/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/ReleaseWithSymbols/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86_64/ReleaseWithSymbols/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/ReleaseWithSymbols/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/ReleaseWithSymbols/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/ReleaseWithSymbols/libhde.a -ltier0 -lvstdlib -ldl
  LDDEPS += ../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86_64/ReleaseWithSymbols/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/ReleaseWithSymbols/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/ReleaseWithSymbols/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86_64/ReleaseWithSymbols/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/ReleaseWithSymbols/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/ReleaseWithSymbols/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/ReleaseWithSymbols/libhde.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../garrysmod_common/sourcesdk-minimal/lib/public/linux64 -L/usr/lib64 -m64 -shared -Wl,-soname=gmsv_luapack_internal_linux64.dll -Wl,--no-undefined
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),releasewithsymbols_x86)
  RESCOMP = windres
  TARGETDIR = x86/ReleaseWithSymbols
  TARGET = $(TARGETDIR)/gmsv_luapack_internal_linux.dll
  OBJDIR = x86/ReleaseWithSymbols/intermediate/gmsv_luapack_internal
  DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DLUAPACK_INTERNAL_SERVER -DIS_SERVERSIDE=true -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"luapack_internal\" -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
  INCLUDES += -I../../../source -isystem ../../../garrysmod_common/include -isystem ../../../garrysmod_common/helpers/include -isystem ../../../garrysmod_common/helpers_extended/include -isystem ../../../garrysmod_common/sourcesdk-minimal/common -isystem ../../../garrysmod_common/sourcesdk-minimal/game/shared -isystem ../../../garrysmod_common/sourcesdk-minimal/public -isystem ../../../garrysmod_common/sourcesdk-minimal/game/server -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier0 -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier1 -isystem ../../../garrysmod_common/scanning/include -isystem ../../../garrysmod_common/detouring/include -isystem ../../../garrysmod_common/detouring/hde/include -isystem ../../../garrysmod_common/detouring/minhook/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -Og -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -g -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/ReleaseWithSymbols/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/ReleaseWithSymbols/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86/ReleaseWithSymbols/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/ReleaseWithSymbols/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/ReleaseWithSymbols/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/ReleaseWithSymbols/libhde.a -ltier0 -lvstdlib -ldl
  LDDEPS += ../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86/ReleaseWithSymbols/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/ReleaseWithSymbols/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/ReleaseWithSymbols/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86/ReleaseWithSymbols/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/ReleaseWithSymbols/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/ReleaseWithSymbols/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/ReleaseWithSymbols/libhde.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../garrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -shared -Wl,-soname=gmsv_luapack_internal_linux.dll -Wl,--no-undefined
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x86_64)
  RESCOMP = windres
  TARGETDIR = x86_64/Release
  TARGET = $(TARGETDIR)/gmsv_luapack_internal_linux64.dll
  OBJDIR = x86_64/Release/intermediate/gmsv_luapack_internal
  DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DLUAPACK_INTERNAL_SERVER -DIS_SERVERSIDE=true -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"luapack_internal\" -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS -DPLATFORM_64BITS
  INCLUDES += -I../../../source -isystem ../../../garrysmod_common/include -isystem ../../../garrysmod_common/helpers/include -isystem ../../../garrysmod_common/helpers_extended/include -isystem ../../../garrysmod_common/sourcesdk-minimal/common -isystem ../../../garrysmod_common/sourcesdk-minimal/game/shared -isystem ../../../garrysmod_common/sourcesdk-minimal/public -isystem ../../../garrysmod_common/sourcesdk-minimal/game/server -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier0 -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier1 -isystem ../../../garrysmod_common/scanning/include -isystem ../../../garrysmod_common/detouring/include -isystem ../../../garrysmod_common/detouring/hde/include -isystem ../../../garrysmod_common/detouring/minhook/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../garrysmod_common/projects/linux/gmake/x86_64/Release/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86_64/Release/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86_64/Release/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/Release/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/Release/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86_64/Release/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/Release/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/Release/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/Release/libhde.a -ltier0 -lvstdlib -ldl
  LDDEPS += ../../../garrysmod_common/projects/linux/gmake/x86_64/Release/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86_64/Release/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86_64/Release/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/Release/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86_64/Release/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86_64/Release/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/Release/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/Release/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86_64/Release/libhde.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../garrysmod_common/sourcesdk-minimal/lib/public/linux64 -L/usr/lib64 -m64 -flto -shared -Wl,-soname=gmsv_luapack_internal_linux64.dll -s -Wl,--no-undefined
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),release_x86)
  RESCOMP = windres
  TARGETDIR = x86/Release
  TARGET = $(TARGETDIR)/gmsv_luapack_internal_linux.dll
  OBJDIR = x86/Release/intermediate/gmsv_luapack_internal
  DEFINES += -D_GLIBCXX_USE_CXX11_ABI=0 -DNDEBUG -DGMMODULE -DLUAPACK_INTERNAL_SERVER -DIS_SERVERSIDE=true -DGMOD_ALLOW_OLD_TYPES -DGMOD_ALLOW_LIGHTUSERDATA -DGMOD_MODULE_NAME=\"luapack_internal\" -DGAME_DLL -DGMOD_USE_SOURCESDK -DRAD_TELEMETRY_DISABLED -DNO_STRING_T -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES -DPROTECTED_THINGS_ENABLE -D_DLL_EXT=.so -DCOMPILER_GCC -DPOSIX -D_POSIX -DLINUX -D_LINUX -DGNUC -DSWDS
  INCLUDES += -I../../../source -isystem ../../../garrysmod_common/include -isystem ../../../garrysmod_common/helpers/include -isystem ../../../garrysmod_common/helpers_extended/include -isystem ../../../garrysmod_common/sourcesdk-minimal/common -isystem ../../../garrysmod_common/sourcesdk-minimal/game/shared -isystem ../../../garrysmod_common/sourcesdk-minimal/public -isystem ../../../garrysmod_common/sourcesdk-minimal/game/server -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier0 -isystem ../../../garrysmod_common/sourcesdk-minimal/public/tier1 -isystem ../../../garrysmod_common/scanning/include -isystem ../../../garrysmod_common/detouring/include -isystem ../../../garrysmod_common/detouring/hde/include -isystem ../../../garrysmod_common/detouring/minhook/include
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu11 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m32 -Wshadow -Wundef -flto -O3 -fPIC -fstrict-aliasing -Wstrict-aliasing=3 -msse2 -Wall -Wextra -std=gnu++17 -Wno-unused-local-typedefs -Wno-unused-parameter -Wno-strict-aliasing -Wno-unknown-pragmas -Wno-undef -Wno-ignored-attributes -Wno-invalid-offsetof
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../../../garrysmod_common/projects/linux/gmake/x86/Release/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86/Release/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86/Release/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/Release/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/Release/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86/Release/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/Release/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/Release/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/Release/libhde.a -ltier0 -lvstdlib -ldl
  LDDEPS += ../../../garrysmod_common/projects/linux/gmake/x86/Release/liblua_shared.a ../../../garrysmod_common/projects/linux/gmake/x86/Release/libhelpers_extended.a ../../../garrysmod_common/projects/linux/gmake/x86/Release/libhelpers.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/Release/libtier1.a ../../../garrysmod_common/sourcesdk-minimal/projects/linux/gmake/x86/Release/libLZMA.a ../../../garrysmod_common/scanning/projects/linux/gmake/x86/Release/libscanning.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/Release/libdetouring.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/Release/libminhook.a ../../../garrysmod_common/detouring/projects/linux/gmake/x86/Release/libhde.a
  ALL_LDFLAGS += $(LDFLAGS) -L../../../garrysmod_common/sourcesdk-minimal/lib/public/linux32 -L/usr/lib32 -m32 -flto -shared -Wl,-soname=gmsv_luapack_internal_linux.dll -s -Wl,--no-undefined
  LINKCMD = $(CXX) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/module.o \
	$(OBJDIR)/interfaces.o \
	$(OBJDIR)/ABICompatibility.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking gmsv_luapack_internal
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning gmsv_luapack_internal
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CXX) -x c++-header $(ALL_CXXFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/module.o: ../../../source/module.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/interfaces.o: ../../../garrysmod_common/sourcesdk-minimal/interfaces/interfaces.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
$(OBJDIR)/ABICompatibility.o: ../../../garrysmod_common/source/ABICompatibility.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(ALL_CXXFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif